<?php declare(strict_types=1);


namespace app\controllers;


use Yii;
use yii\web\Controller;

/**
 * 前台基类控制器
 *
 * Class FrontController
 * @package app\controllers
 */
class FrontController extends Controller
{
    public $request;

    public $response;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        $this->response = Yii::$app->response;
        Yii::$app->request->parsers = [
            'application/json' => 'yii\web\JsonParser',
            'text/json'        => 'yii\web\JsonParser',
        ];
    }
}