<?php declare(strict_types=1);


namespace app\controllers;


use app\service\AccessRecordService;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Request;
use yii\web\Response;

/**
 * 前台基类控制器
 *
 * Class FrontController
 * @package app\controllers
 * @property Request $request
 * @property Response $response
 */
class FrontController extends Controller
{
    /** @var  */
    public $request;

    public $response;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request  = Yii::$app->request;
        $this->response = Yii::$app->response;
        Yii::$app->request->parsers = [
            'application/json' => 'yii\web\JsonParser',
            'text/json'        => 'yii\web\JsonParser',
        ];
    }

    /**
     * 重写beforeAction
     *
     * Date: 2020/5/8
     * @author chentulin
     * @param $action
     * @return bool
     */
    public function beforeAction($action)
    {
        try {
            // 获取访问的博客的地址
            $params['ip']               = (string)Yii::$app->request->userIP;
            $params['access_url']              = $this->request->url;
            $params['access_time']      = time();
            AccessRecordService::record($params);
            return parent::beforeAction($action);
        } catch (BadRequestHttpException $e) {
        } // TODO: Change the autogenerated stub
    }
}