<?php declare(strict_types=1);

namespace app\commands;

use app\models\Role;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use app\models\AdminUser;
use app\models\RoleJurisdiction;
use yii\web\Request;
use yii\web\Response;

/**
 * Class BaseController
 * @package app\commands
 * @property Request $request
 * @property Response $response
 */
class BaseController extends Controller
{

    public $layout = false;

    public $request;

    public $response;

    public function init()
    {
        // 时区设置为东八区
        date_default_timezone_set('etc/gmt-8');
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        $this->response = Yii::$app->response;
        Yii::$app->request->parsers = [
            'application/json' => 'yii\web\JsonParser',
            'text/json'        => 'yii\web\JsonParser',
        ];
    }

    public function beforeAction($action)
    {
        $userId = Yii::$app->session->get('user');
        if ( !$userId ){
           return $this->redirect('/backend/login/login');
        }
        // 检查用户是否有这个权限 我的权限直接跳过权限认证
        if ($userId !== 'chentulinys@163.com' ){
            $controllerName = explode('/', $action->controller->id)[1];
            $actionName = $action->id;
            $route = $controllerName.'/'.$actionName;
            $roleId = AdminUser::findRole($userId);
            // 根据角色id找出所有id
            $roleArr = Role::findArrByRoleId($roleId);
            $roleRead = [];
            foreach ($roleArr as $key => $value){
                $one = RoleJurisdiction::findById($value);
                $roleRead[$key] = $one['controller'].'/'.$one['action'];
            }
            if (!in_array($route, $roleRead, true)){
                echo '你没有权限访问,请向管理员申请权限';
                die();
            }
        }
        try {
            return parent::beforeAction($action);
        } catch (BadRequestHttpException $e) {
            return $e->getMessage();
        } // TODO: Change the autogenerated stub
    }
}