<?php declare(strict_types=1);


namespace app\commands;

use Yii;
use yii\web\Controller;

/**
 * Class BaseController
 * @package app\commands
 */
class BaseController extends Controller
{
    public function beforeAction($action)
    {
        $userId = Yii::$app->session->get('user');
        if ( !$userId ){
            $this->redirect('/backend/login/login');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}