<?php declare(strict_types=1);

namespace app\commands;

use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use app\models\AdminUser;
use app\models\RoleJurisdiction;

/**
 * Class BaseController
 * @package app\commands
 */
class BaseController extends Controller
{
    public function beforeAction($action)
    {
        $userId = Yii::$app->session->get('user');
        if ( !$userId ){
           return $this->redirect('/backend/login/login');
        }
        // 检查用户是否有这个权限 我的权限直接跳过权限认证
        if ($userId !== 'chentulinys@163.com' ){
            $controllerName = explode('/', $action->controller->id)[1];
            $actionName = $action->id;
            $route = $controllerName.'/'.$actionName;
            $roleId = AdminUser::findRole($userId);
            // 根据角色id找出所有id
            $roleArr = RoleJurisdiction::findArrByRoleId($roleId);
            $roleRead = [];
            foreach ($roleArr as $key => $value){
                $roleRead[$key] = $value['controller'].'/'.$value['action'];
            }
            if (!in_array($route, $roleRead, true)){
                echo '你没有权限访问,请向管理员申请权限';
                die();
            }
        }
        try {
            return parent::beforeAction($action);
        } catch (BadRequestHttpException $e) {
            return $e->getMessage();
        } // TODO: Change the autogenerated stub
    }
}