<?php declare(strict_types=1);


namespace app\components;


use Yii;
use yii\web\BadRequestHttpException;
use yii\web\ErrorHandler;
use yii\web\NotFoundHttpException;

/**
 * 统一异常处理器
 *
 * Class ExceptionHandler
 * @package yii\components
 */
class ExceptionHandler extends ErrorHandler
{
    /**
     * 统一异常处理方法
     *
     * Date: 2020/5/8
     * @param \Exception $exception
     * @return void
     * @author chentulin
     */
    public function handleException($exception)
    {
        if ($exception instanceof NotFoundHttpException){
            Yii::$app->getResponse()->redirect('/front/index/index')->send();
            return;
        }
        if ($exception instanceof BadRequestHttpException){
            Yii::$app->getResponse()->redirect('/front/index/index')->send();
            return;
        }
        return parent::handleException($exception); // TODO: Change the autogenerated stub
    }
}